name: local_database
description: Local database module

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  moor: ^3.0.2
  data:
    path: ../data

dev_dependencies:
  test: ^1.14.2