name: app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  core:
    path: core
  presentation:
    path: presentation
  domain:
    path: domain
  data:
    path: data

  flutter:
    sdk: flutter  

  get_it: ^4.0.2
  data_connection_checker: ^0.3.4
  http: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg