name: core
description: A shared core that helps to structure the app.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  equatable: ^1.1.1
  data_connection_checker: ^0.3.4
  
dev_dependencies:
  mockito: ^4.1.1
  test: ^1.14.2